
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobilefirst-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobilefirst-portfolio
  template:
    metadata:
      labels:
        app: mobilefirst-portfolio
    spec:
      containers:
      - name: mobilefirst-portfolio
        image: 135808923653.dkr.ecr.us-east-1.amazonaws.com/mobilefirst/portfolio:1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mobilefirst-portfolio-service
spec:
  selector:
    app: mobilefirst-portfolio
  ports:
  - protocol: TCP
    port: 80                
    targetPort: 3000
  type: LoadBalancer
