
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobilefirst-kyc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mobilefirst-kyc
  template:
    metadata:
      labels:
        app: mobilefirst-kyc
    spec:
      containers:
      - name: mobilefirst-kyc
        image:
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mobilefirst-kyc-service
spec:
  selector:
    app: mobilefirst-kyc
  ports:
  - protocol: TCP
    port: 80                
    targetPort: 3000
  type: LoadBalancer
